[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api/questions/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8081"
JAVA_OPTS = "-Xmx512m -Xms256m"
