services:
  - type: web
    name: quiz-question-service
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 8081
      - key: SPRING_DATA_MONGODB_URI
        sync: false
    healthCheck:
      path: /actuator/health
      initialDelaySeconds: 30
      periodSeconds: 10
