server.port=8081
server.address=0.0.0.0

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://kngdivyansh1_db_user:0IgPgJPdTCnZh4nE@authservice.fhxpenv.mongodb.net/?appName=AuthService
spring.data.mongodb.database=quiz_application
