server.port=8080
server.address=0.0.0.0

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://kngdivyansh1_db_user:0IgPgJPdTCnZh4nE@authservice.fhxpenv.mongodb.net/?appName=AuthService
spring.data.mongodb.database=quiz_application

# Base64-encoded 256-bit secret (change in prod)
jwt.secret=ZmFrZV9zdXBlcl9sb25nX3NlY3JldF9rZXlfMzJfY2hhcnNfbWluaW11bQ==
